### ISSUE TITLE
api/auth/signup 중복 이메일 문제

### ISSUE THREAD

**Issue by mvvkinn** [mvvkinn/interview-system#21]
## 목적
api/auth/signup에서 중복된 이메일을 입력해도 회원가입이 되는 문제 해결

## 상세내용
User 테이블 unique 제약사항 추가
이메일 중복 확인 api 생성
회원가입 페이지 이메일 중복 확인 체크

## 참고사항
-

**Comment by mvvkinn** [comment]
>> User 테이블 unique 제약사항 추가
* 해결완료, phone에도 unique 제약사항 추가함

**Comment by taemin-jang** [comment]
이메일 중복 확인만 할 수는 없을까요?

signin으로 이메일만 보내면 중복일 때랑 아닐 때 error 메세지는 다르지만 http 코드는 401로 통일이라 에러 핸들링으로 체크가 안되는 것 같아요

**Comment by taemin-jang** [comment]
그리고 아직 중복으로 입력해도 회원가입이 진행되는거 같아요

확인 부탁드려요

**Comment by mvvkinn** [comment]
> 이메일 중복 확인 api 생성
* api/auth/emailDuplication
* 생성완료
